/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
// alterado da web
// Commit de teste

import connection.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.Alert;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataListener;
import javax.swing.table.DefaultTableModel;
import model.bean.Carro;
import model.bean.Cliente;
import model.bean.Cor;
import model.bean.Telefone;
import model.dao.CarroDao;
import model.dao.Carro_Cor_Dao;
import model.dao.ClienteDao;
import model.dao.Cliente_Telefone_Dao;
import model.dao.CorDao;
import model.dao.TelefoneDao;

/**
 *
 * @author Denilson
 */
public class Cadastro extends javax.swing.JFrame {
    
    private String placa;
    private String numero;
    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
        
        
        
        jLayeredCadastrar.setVisible(false);
        jLayeredMain.setVisible(true);
        jLayeredConsultar.setVisible(false);
        jLayeredAlterar.setVisible(false);
        
        ValidationModelo.setVisible(false);
        ValidationCor.setVisible(false);
        ValidationNome.setVisible(false);
        ValidationPlaca.setVisible(false);
        ValidationTelefone.setVisible(false);
        
        atualizarComboBox();
        
        
       // jCbCor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLayeredMain = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jBmain_Cadastrar = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jBmain_Consultar = new javax.swing.JButton();
        jLayeredCadastrar = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        bSalvar = new javax.swing.JButton();
        bVoltar = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTxtTelefone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCbSexo = new javax.swing.JComboBox<>();
        ValidationNome = new javax.swing.JLabel();
        ValidationTelefone = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTxtPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxtModelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCbCor = new javax.swing.JComboBox<>();
        jCheckBoxCadCor = new javax.swing.JCheckBox();
        jTfNovaCor = new javax.swing.JTextField();
        ValidationModelo = new javax.swing.JLabel();
        ValidationPlaca = new javax.swing.JLabel();
        ValidationCor = new javax.swing.JLabel();
        jLayeredConsultar = new javax.swing.JLayeredPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTfConsullta = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jBbuscar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jBvoltar = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jBdeletar = new javax.swing.JButton();
        jLayeredAlterar = new javax.swing.JLayeredPane();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        bSalvar1 = new javax.swing.JButton();
        bVoltar1 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTxtNome1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTxtTelefone1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jCbSexo1 = new javax.swing.JComboBox<>();
        ValidationNome1 = new javax.swing.JLabel();
        ValidationTelefone1 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTxtPlaca1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTxtModelo1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jCbCor1 = new javax.swing.JComboBox<>();
        jCheckBoxCadCor1 = new javax.swing.JCheckBox();
        jTfNovaCor1 = new javax.swing.JTextField();
        ValidationModelo1 = new javax.swing.JLabel();
        ValidationPlaca1 = new javax.swing.JLabel();
        ValidationCor1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel11.setText("jLabel11");

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Oficina do Sr. José");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        jBmain_Cadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBmain_Cadastrar.setText("Cadastrar");
        jBmain_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmain_CadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jBmain_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jBmain_Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        jBmain_Consultar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBmain_Consultar.setText("Consultar");
        jBmain_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmain_ConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jBmain_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jBmain_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredMain.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredMain.setLayer(jPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredMain.setLayer(jPanel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredMain.setLayer(jPanel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredMainLayout = new javax.swing.GroupLayout(jLayeredMain);
        jLayeredMain.setLayout(jLayeredMainLayout);
        jLayeredMainLayout.setHorizontalGroup(
            jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredMainLayout.createSequentialGroup()
                .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jLayeredMainLayout.setVerticalGroup(
            jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredMainLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(jLayeredMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredMainLayout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jLayeredMainLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );

        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bVoltar.setText("Voltar");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bVoltar)
                .addGap(18, 18, 18)
                .addComponent(bSalvar)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar)
                    .addComponent(bVoltar))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel6.setText("Nome");

        jLabel7.setText("Telefone");

        jLabel8.setText("Sexo");

        jCbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        jCbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbSexoActionPerformed(evt);
            }
        });

        ValidationNome.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ValidationNome.setForeground(java.awt.Color.red);
        ValidationNome.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValidationNome.setText("*");

        ValidationTelefone.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ValidationTelefone.setForeground(java.awt.Color.red);
        ValidationTelefone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValidationTelefone.setText("*");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtNome)
                            .addComponent(jTxtTelefone)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jCbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 170, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValidationTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValidationNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(ValidationNome, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(ValidationTelefone)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jCbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Carro"));

        jLabel3.setText("Placa");

        jLabel4.setText("Modelo");

        jLabel5.setText("Cor");

        jCbCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbCorActionPerformed(evt);
            }
        });

        jCheckBoxCadCor.setText("Cadastrar nova cor");
        jCheckBoxCadCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCadCorActionPerformed(evt);
            }
        });

        ValidationModelo.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ValidationModelo.setForeground(java.awt.Color.red);
        ValidationModelo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValidationModelo.setText("*");

        ValidationPlaca.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ValidationPlaca.setForeground(java.awt.Color.red);
        ValidationPlaca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValidationPlaca.setText("*");

        ValidationCor.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ValidationCor.setForeground(java.awt.Color.red);
        ValidationCor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValidationCor.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(ValidationCor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPlaca)
                            .addComponent(jTxtModelo)
                            .addComponent(jTfNovaCor)
                            .addComponent(jCbCor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 170, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCadCor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ValidationModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValidationPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(ValidationPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ValidationModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCbCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxCadCor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfNovaCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValidationCor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredCadastrar.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredCadastrar.setLayer(jPanel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredCadastrar.setLayer(jPanel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredCadastrarLayout = new javax.swing.GroupLayout(jLayeredCadastrar);
        jLayeredCadastrar.setLayout(jLayeredCadastrarLayout);
        jLayeredCadastrarLayout.setHorizontalGroup(
            jLayeredCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredCadastrarLayout.setVerticalGroup(
            jLayeredCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredCadastrarLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Consulta");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(20, 20, 20))
        );

        jLabel10.setText("Nome:");

        jTfConsullta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTfConsulltaKeyPressed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Sexo", "Modelo do Carro", "Placa", "Cor", "Contato"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });
        jBbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBbuscarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTfConsullta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBbuscar)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTfConsullta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        jBvoltar.setText("Voltar");
        jBvoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvoltarActionPerformed(evt);
            }
        });

        jBalterar.setText("Alterar");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBdeletar.setText("Deletar");
        jBdeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBdeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBdeletar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBalterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBvoltar)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBdeletar)
                    .addComponent(jBalterar)
                    .addComponent(jBvoltar))
                .addContainerGap())
        );

        jLayeredConsultar.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredConsultar.setLayer(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredConsultar.setLayer(jPanel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredConsultarLayout = new javax.swing.GroupLayout(jLayeredConsultar);
        jLayeredConsultar.setLayout(jLayeredConsultarLayout);
        jLayeredConsultarLayout.setHorizontalGroup(
            jLayeredConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredConsultarLayout.setVerticalGroup(
            jLayeredConsultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredConsultarLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        jPanel15.setBackground(new java.awt.Color(0, 51, 51));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Alterar");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(20, 20, 20))
        );

        bSalvar1.setText("Salvar");
        bSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvar1ActionPerformed(evt);
            }
        });

        bVoltar1.setText("Voltar");
        bVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bVoltar1)
                .addGap(18, 18, 18)
                .addComponent(bSalvar1)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar1)
                    .addComponent(bVoltar1))
                .addContainerGap())
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabel13.setText("Nome");

        jLabel14.setText("Telefone");

        jLabel15.setText("Sexo");

        jCbSexo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        jCbSexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbSexo1ActionPerformed(evt);
            }
        });

        ValidationNome1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ValidationNome1.setForeground(java.awt.Color.red);
        ValidationNome1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValidationNome1.setText("*");

        ValidationTelefone1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ValidationTelefone1.setForeground(java.awt.Color.red);
        ValidationTelefone1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValidationTelefone1.setText("*");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtNome1)
                            .addComponent(jTxtTelefone1)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(jCbSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 170, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ValidationTelefone1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValidationNome1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(ValidationNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTxtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(ValidationTelefone1)
                .addGap(1, 1, 1)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTxtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jCbSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Carro"));

        jLabel16.setText("Placa");

        jLabel17.setText("Modelo");

        jLabel18.setText("Cor");

        jCbCor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbCor1ActionPerformed(evt);
            }
        });

        jCheckBoxCadCor1.setText("Cadastrar nova cor");
        jCheckBoxCadCor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxCadCor1ActionPerformed(evt);
            }
        });

        ValidationModelo1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ValidationModelo1.setForeground(java.awt.Color.red);
        ValidationModelo1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValidationModelo1.setText("*");

        ValidationPlaca1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ValidationPlaca1.setForeground(java.awt.Color.red);
        ValidationPlaca1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValidationPlaca1.setText("*");

        ValidationCor1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ValidationCor1.setForeground(java.awt.Color.red);
        ValidationCor1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ValidationCor1.setText("*");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(ValidationCor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPlaca1)
                            .addComponent(jTxtModelo1)
                            .addComponent(jTfNovaCor1)
                            .addComponent(jCbCor1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addGap(0, 170, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxCadCor1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ValidationModelo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ValidationPlaca1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(ValidationPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTxtPlaca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ValidationModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTxtModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jCbCor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBoxCadCor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTfNovaCor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValidationCor1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredAlterar.setLayer(jPanel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredAlterar.setLayer(jPanel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredAlterar.setLayer(jPanel17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredAlterarLayout = new javax.swing.GroupLayout(jLayeredAlterar);
        jLayeredAlterar.setLayout(jLayeredAlterarLayout);
        jLayeredAlterarLayout.setHorizontalGroup(
            jLayeredAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredAlterarLayout.setVerticalGroup(
            jLayeredAlterarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredAlterarLayout.createSequentialGroup()
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredMain)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredConsultar)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredCadastrar))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredAlterar)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredMain)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredConsultar)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredCadastrar))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredAlterar)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizarComboBox(){
        jCbCor.removeAllItems();
        jCbCor1.removeAllItems();
        
        Connection con = ConnectionFactory.getConnection();
       
        PreparedStatement stmt = null;
        ResultSet rs = null;
        
        
        try {
            stmt = con.prepareStatement("USE OFICINA");
            stmt.executeQuery();
            
            stmt = con.prepareStatement("SELECT COR FROM COR");          
            rs = stmt.executeQuery();
            
            while (rs.next()) {                
                jCbCor.addItem(rs.getString("COR"));
                jCbCor1.addItem(rs.getString("COR"));
            }
     
        } catch (SQLException ex) {
            Logger.getLogger(CarroDao.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            ConnectionFactory.closeConnection(con, stmt, rs);
        }
    }
    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        jLayeredCadastrar.setVisible(false);
        jLayeredMain.setVisible(true);
        jLayeredConsultar.setVisible(false);
        jLayeredAlterar.setVerifyInputWhenFocusTarget(false);
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
       
    // CRIAR E INICIALIZAR OBJETOS  
    
    Carro c = new Carro();
        
        c.setPlaca(jTxtPlaca.getText());
        c.setModelo(jTxtModelo.getText());
    
    Cliente cl = new Cliente();
        
        cl.setNome(jTxtNome.getText());
        cl.setSexo(jCbSexo.getSelectedIndex());
        
    
    Telefone te = new Telefone();
        
        te.setNumero(jTxtTelefone.getText());
        
    Cor co = new Cor();        
 
            if (jCheckBoxCadCor.isSelected()) {
                co.setCor(jTfNovaCor.getText());
            } else {
                co.setCor((String)jCbCor.getSelectedItem());
            }    
    // VALIDADAR ENTRADA
        
        if (c.modeloIsReady() && c.placaIsReady(true) && cl.isReady() && te.isReady() && 
           ((!jCheckBoxCadCor.isSelected()) || (jCheckBoxCadCor.isSelected() && co.isReady()))){
    
        // INSERIR NO BANCO
            System.out.println("Inserindo no banco só de mentirinha...");
            
            c.setIdcarro(CarroDao.create(c));  
                try {
                    cl.setCarro(c);
                } catch (SQLException ex) {
                    Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
                }
            cl.setIdcliente(ClienteDao.create(cl));
            te.setIdtelefone(TelefoneDao.create(te));

            if (jCheckBoxCadCor.isSelected()) {
                co.setIdcor(CorDao.create(co));
            } else {
                co.setIdcor(CorDao.createId(co));
            }

            Carro_Cor_Dao.create(c.getIdcarro(), co.getIdcor());
            Cliente_Telefone_Dao.create(cl.getIdcliente(), te.getIdtelefone());                
        
        // LIMPAR CAMPOS
    
        jTxtNome.setText("");
        jTxtModelo.setText("");
        jTxtPlaca.setText("");
        jTxtTelefone.setText("");
        jTfNovaCor.setText("");
        ValidationModelo.setVisible(false);
        ValidationCor.setVisible(false);
        ValidationNome.setVisible(false);
        ValidationPlaca.setVisible(false);
        ValidationTelefone.setVisible(false);

        atualizarComboBox();

        } else {
            System.out.println("Entrada invalida");
            
            if (!c.modeloIsReady()) {
                ValidationModelo.setVisible(true);
            } else {
                ValidationModelo.setVisible(false);
            }
            
            if (!c.placaIsReady(true)) {
                ValidationPlaca.setVisible(true);
            } else {
                ValidationPlaca.setVisible(false);
            }
            
            if (!cl.isReady()) {
                ValidationNome.setVisible(true);
            } else {
                ValidationNome.setVisible(false);
            }
            
            if (!te.isReady()) {
                ValidationTelefone.setVisible(true);
            } else {
                ValidationTelefone.setVisible(false);
            }
            
            if (jCheckBoxCadCor.isSelected() && !co.isReady()) {
                ValidationCor.setVisible(true);
            } else {
                ValidationCor.setVisible(false);
            }   
        }        
    }//GEN-LAST:event_bSalvarActionPerformed

    private void jCbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbSexoActionPerformed

    private void jCbCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbCorActionPerformed

    private void jCheckBoxCadCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCadCorActionPerformed
        if (jCheckBoxCadCor.isSelected()) {
            jTfNovaCor.setVisible(true);
        } else{
            jTfNovaCor.setVisible(false);
            ValidationCor.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxCadCorActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        this.atualizarComboBox();
        
        ValidationModelo1.setVisible(false);
        ValidationCor1.setVisible(false);
        ValidationNome1.setVisible(false);
        ValidationPlaca1.setVisible(false);
        ValidationTelefone1.setVisible(false);
        
        if (jTable2.getSelectedRow() > -1) {
              
            Object[] obj = new Object[6];

            for (int colunm = 0; colunm < 6; colunm++) {
                obj[colunm] = jTable2.getValueAt(jTable2.getSelectedRow(), colunm);
            }

    //        for (int colunm = 0; colunm < 6; colunm++) {
    //            System.out.println(obj[colunm]);
    //        }

            jLayeredMain.setVisible(false);
            jLayeredCadastrar.setVisible(false);
            jLayeredConsultar.setVisible(false);
            jLayeredAlterar.setVisible(true);

        // AUTO-PREENCHIMENTO

            jTxtNome1.setText(obj[0].toString());

            if (obj[1].toString().equalsIgnoreCase("M")) {
                jCbSexo1.setSelectedIndex(1);
            } else {
                jCbSexo1.setSelectedIndex(0);
            }

            jTxtModelo1.setText(obj[2].toString());
            jTxtPlaca1.setText(obj[3].toString());
            this.placa = obj[3].toString();
            
            for (int i = 0; i < jCbCor1.getItemCount(); i++) {
                
                if (jCbCor1.getItemAt(i).toString().equalsIgnoreCase(obj[4].toString())) {  
                    jCbCor1.setSelectedIndex(i);
                } 
            }

            jTxtTelefone1.setText(obj[5].toString());
            this.numero = obj[5].toString();
            
        } else {
            System.out.println("Nenhuma linha selecionada");
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor selecione um registro para alterar!", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBalterarActionPerformed

    private void jBvoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvoltarActionPerformed
        jLayeredCadastrar.setVisible(false);
        jLayeredMain.setVisible(true);
        jLayeredConsultar.setVisible(false);
        jLayeredAlterar.setVisible(false);
    }//GEN-LAST:event_jBvoltarActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        if (jTfConsullta.getText().equals("")) {
            jBmain_ConsultarActionPerformed(evt);
        } else {
        
            Connection con = ConnectionFactory.getConnection();
            ResultSet rs = null;
            PreparedStatement stmt = null;

            try {
                stmt = con.prepareStatement
                ("SELECT CL.NOME AS CLIENTE, \n" +
                    "	CL.SEXO, \n" +
                    "	CA.MODELO AS \"MODELO DO CARRO\", \n" +
                    "	CA.PLACA, CO.COR, \n" +
                    "	TE.NUMERO AS CONTATO\n" +
                    "FROM CLIENTE CL\n" +
                    "INNER JOIN CARRO CA\n" +
                    "ON CA.IDCARRO = CL.ID_CARRO\n" +
                    "INNER JOIN COR CO\n" +
                    "INNER JOIN CARRO_COR CC\n" +
                    "ON CC.ID_CARRO = CA.IDCARRO AND CC.ID_COR = CO.IDCOR\n" +
                    "INNER JOIN TELEFONE TE\n" +
                    "INNER JOIN CLIENTE_TELEFONE CT\n" +
                    "ON CT.ID_CLIENTE = CL.IDCLIENTE AND CT.ID_TELEFONE = TE.IDTELEFONE\n" +
                    "WHERE CL.NOME = ?");

                stmt.setString(1, jTfConsullta.getText());

                rs = stmt.executeQuery();

                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setNumRows(0);

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("CLIENTE"),
                        rs.getString("SEXO"),
                        rs.getString("MODELO DO CARRO"),
                        rs.getString("PLACA"),
                        rs.getString("COR"),
                        rs.getString("CONTATO")
                    });
                }

            } catch (SQLException ex) {
                System.out.println("Problema ao buscar no Banco: " + ex.getMessage());
            } finally {
                ConnectionFactory.closeConnection(con, stmt, rs);
            }
        }
        jTfConsullta.setText("");
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBmain_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmain_ConsultarActionPerformed
        jTable2.setColumnSelectionAllowed(false);
        
        Connection con = ConnectionFactory.getConnection();
        ResultSet rs = null;
        PreparedStatement stmt = null;
        
        try {
            stmt = con.prepareStatement
            ("SELECT CL.NOME AS CLIENTE, \n" +
                "	CL.SEXO, \n" +
                "	CA.MODELO AS \"MODELO DO CARRO\", \n" +
                "	CA.PLACA, CO.COR, \n" +
                "	TE.NUMERO AS CONTATO\n" +
                "FROM CLIENTE CL\n" +
                "INNER JOIN CARRO CA\n" +
                "ON CA.IDCARRO = CL.ID_CARRO\n" +
                "INNER JOIN COR CO\n" +
                "INNER JOIN CARRO_COR CC\n" +
                "ON CC.ID_CARRO = CA.IDCARRO AND CC.ID_COR = CO.IDCOR\n" +
                "INNER JOIN TELEFONE TE\n" +
                "INNER JOIN CLIENTE_TELEFONE CT\n" +
                "ON CT.ID_CLIENTE = CL.IDCLIENTE AND CT.ID_TELEFONE = TE.IDTELEFONE;");

            rs = stmt.executeQuery();

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setNumRows(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("CLIENTE"),
                    rs.getString("SEXO"),
                    rs.getString("MODELO DO CARRO"),
                    rs.getString("PLACA"),
                    rs.getString("COR"),
                    rs.getString("CONTATO")
                });
            }

        } catch (SQLException ex) {
            System.out.println("Problema ao buscar no Banco: " + ex.getMessage());
        } finally {
            ConnectionFactory.closeConnection(con, stmt, rs);
        }

        jLayeredConsultar.setVisible(true);
        jLayeredMain.setVisible(false);
        jLayeredCadastrar.setVisible(false);
        jLayeredAlterar.setVisible(false);
    }//GEN-LAST:event_jBmain_ConsultarActionPerformed

    private void jBmain_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmain_CadastrarActionPerformed
        jLayeredCadastrar.setVisible(true);
        jLayeredMain.setVisible(false);
        jLayeredConsultar.setVisible(false);
    }//GEN-LAST:event_jBmain_CadastrarActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jBdeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBdeletarActionPerformed
//        System.out.println(jTable2.getSelectedRow());
        

        if (jTable2.getSelectedRow() > -1) { 
            Connection con = ConnectionFactory.getConnection();
        
            PreparedStatement stmt = null;
            ResultSet rs = null;

            try {
                stmt = con.prepareStatement("USE OFICINA");
                stmt.executeQuery(); 
                
                stmt = con.prepareStatement("DELETE FROM CARRO_COR WHERE ID_CARRO = "
                        + "(SELECT IDCARRO FROM CARRO WHERE PLACA = ?)");
                stmt.setString(1,(String) jTable2.getValueAt(jTable2.getSelectedRow(), 3));
                stmt.executeUpdate();
                
                stmt = con.prepareStatement("DELETE FROM CLIENTE_TELEFONE WHERE ID_CLIENTE = "
                        + "(SELECT IDCLIENTE FROM CLIENTE WHERE ID_CARRO = "
                        + "(SELECT IDCARRO FROM CARRO WHERE PLACA = ?))");
                stmt.setString(1,(String) jTable2.getValueAt(jTable2.getSelectedRow(), 3));
                stmt.executeUpdate();
                
                stmt = con.prepareStatement("DELETE FROM CLIENTE WHERE ID_CARRO = "
                        + "(SELECT IDCARRO FROM CARRO WHERE PLACA = ?)");
                stmt.setString(1,(String) jTable2.getValueAt(jTable2.getSelectedRow(), 3));
                stmt.executeUpdate();
                
                stmt = con.prepareStatement("DELETE FROM CARRO WHERE PLACA = ?");
                stmt.setString(1,(String) jTable2.getValueAt(jTable2.getSelectedRow(), 3));
                stmt.executeUpdate();
                
                jBmain_ConsultarActionPerformed(evt);
            } catch (SQLException ex) {
                Logger.getLogger(CarroDao.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                ConnectionFactory.closeConnection(con, stmt, rs);
        }
                    
        } else {
            System.out.println("Nenhuma linha selecionada!");
        }
        
        
        
    }//GEN-LAST:event_jBdeletarActionPerformed

    private void bSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvar1ActionPerformed
    
// CRIAR E INICIALIZAR OBJETOS  
        
        if (jTable2.getSelectedRow() > -1) {
         
            Carro c = new Carro();

                c.setPlaca(jTxtPlaca1.getText());
                c.setModelo(jTxtModelo1.getText());

            Cliente cl = new Cliente();

                cl.setNome(jTxtNome1.getText());
                cl.setSexo(jCbSexo1.getSelectedIndex());


            Telefone te = new Telefone();

                te.setNumero(jTxtTelefone1.getText());

            Cor co = new Cor();        

                    if (jCheckBoxCadCor1.isSelected()) {
                        co.setCor(jTfNovaCor1.getText());
                    } else {
                        co.setCor((String)jCbCor1.getSelectedItem());
                    }    
            // VALIDADAR ENTRADA

                if (c.modeloIsReady() && c.placaIsReady(false) && cl.isReady() && te.isReady() && 
                   ((!jCheckBoxCadCor1.isSelected()) || (jCheckBoxCadCor1.isSelected() && co.isReady()))){

                // ALTERA NO BANCO

                    ClienteDao.update(this.placa, cl);
                    CarroDao.update(placa, c);
                    if (jCheckBoxCadCor1.isSelected()) {
                        CorDao.update(placa, co);
                    } else {
                        CorDao.updateId(placa, co);
                    }
                    TelefoneDao.update(numero, te);

                // LIMPAR CAMPOS

                    jTxtNome1.setText("");
                    jTxtModelo1.setText("");
                    jTxtPlaca1.setText("");
                    jTxtTelefone1.setText("");
                    jTfNovaCor1.setText("");
                    ValidationModelo1.setVisible(false);
                    ValidationCor1.setVisible(false);
                    ValidationNome1.setVisible(false);
                    ValidationPlaca1.setVisible(false);
                    ValidationTelefone1.setVisible(false);

                    jBmain_ConsultarActionPerformed(evt);
                    
                } else {
                    System.out.println("Entrada invalida");

                    if (!c.modeloIsReady()) {
                        ValidationModelo1.setVisible(true);
                    } else {
                        ValidationModelo1.setVisible(false);
                    }

                    if (!c.placaIsReady(false)) {
                        ValidationPlaca1.setVisible(true);
                    } else {
                        ValidationPlaca1.setVisible(false);
                    }

                    if (!cl.isReady()) {
                        ValidationNome1.setVisible(true);
                    } else {
                        ValidationNome1.setVisible(false);
                    }

                    if (!te.isReady()) {
                        ValidationTelefone1.setVisible(true);
                    } else {
                        ValidationTelefone1.setVisible(false);
                    }

                    if (jCheckBoxCadCor1.isSelected() && !co.isReady()) {
                        ValidationCor1.setVisible(true);
                    } else {
                        ValidationCor1.setVisible(false);
                    }   
                }
        } else {
            System.out.println("Nenhuma linha selecionada!");
        }
    }//GEN-LAST:event_bSalvar1ActionPerformed

    private void bVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltar1ActionPerformed
        
        jBmain_ConsultarActionPerformed(evt);
    }//GEN-LAST:event_bVoltar1ActionPerformed

    private void jCbSexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbSexo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbSexo1ActionPerformed

    private void jCbCor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbCor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbCor1ActionPerformed

    private void jCheckBoxCadCor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCadCor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxCadCor1ActionPerformed

    private void jTfConsulltaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTfConsulltaKeyPressed
       
    }//GEN-LAST:event_jTfConsulltaKeyPressed

    private void jBbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBbuscarKeyPressed
       
    }//GEN-LAST:event_jBbuscarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ValidationCor;
    private javax.swing.JLabel ValidationCor1;
    private javax.swing.JLabel ValidationModelo;
    private javax.swing.JLabel ValidationModelo1;
    private javax.swing.JLabel ValidationNome;
    private javax.swing.JLabel ValidationNome1;
    private javax.swing.JLabel ValidationPlaca;
    private javax.swing.JLabel ValidationPlaca1;
    private javax.swing.JLabel ValidationTelefone;
    private javax.swing.JLabel ValidationTelefone1;
    private javax.swing.JButton bSalvar;
    private javax.swing.JButton bSalvar1;
    private javax.swing.JButton bVoltar;
    private javax.swing.JButton bVoltar1;
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBdeletar;
    private javax.swing.JButton jBmain_Cadastrar;
    private javax.swing.JButton jBmain_Consultar;
    private javax.swing.JButton jBvoltar;
    private javax.swing.JComboBox<Object> jCbCor;
    private javax.swing.JComboBox<Object> jCbCor1;
    private javax.swing.JComboBox<String> jCbSexo;
    private javax.swing.JComboBox<String> jCbSexo1;
    private javax.swing.JCheckBox jCheckBoxCadCor;
    private javax.swing.JCheckBox jCheckBoxCadCor1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredAlterar;
    private javax.swing.JLayeredPane jLayeredCadastrar;
    private javax.swing.JLayeredPane jLayeredConsultar;
    private javax.swing.JLayeredPane jLayeredMain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTfConsullta;
    private javax.swing.JTextField jTfNovaCor;
    private javax.swing.JTextField jTfNovaCor1;
    private javax.swing.JTextField jTxtModelo;
    private javax.swing.JTextField jTxtModelo1;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtNome1;
    private javax.swing.JTextField jTxtPlaca;
    private javax.swing.JTextField jTxtPlaca1;
    private javax.swing.JTextField jTxtTelefone;
    private javax.swing.JTextField jTxtTelefone1;
    // End of variables declaration//GEN-END:variables
}
